### Algorythms comparision

In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [26]:
data = np.load(r'C:\Users\glabm\Desktop\Credit approval project\Credit-approval-project\data\03_processed\normalized_data.npy')
df = pd.DataFrame(data)
df = df.rename(columns={1:'Income', 2:'Age', 3:'Experience', 4:'CURRENT_JOB_YRS', 5:'CURRENT_HOUSE_YRS'})
df1 = pd.read_csv(r'C:\Users\glabm\Desktop\Credit approval project\Credit-approval-project\data\02_interim\categorical_data.csv')
df1.head()

,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,Risk_Flag
0,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,0
1,single,rented,no,Software_Developer,Parbhani,Maharashtra,0
2,married,rented,no,Technical_writer,Alappuzha,Kerala,0
3,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,1
4,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,1

In [31]:
final_df = pd.concat([df, df1], axis=1)
final_df.drop(0, axis=1, inplace=True)
final_df.head()

,Income,Age,Experience,CURRENT_JOB_YRS,CURRENT_HOUSE_YRS,Married/Single,House_Ownership,Car_Ownership,Profession,CITY,STATE,Risk_Flag
0,0.034483,0.15,0.214286,0.75,0.0,single,rented,no,Mechanical_engineer,Rewa,Madhya_Pradesh,0
1,0.327586,0.50,0.642857,0.75,0.0,single,rented,no,Software_Developer,Parbhani,Maharashtra,0
2,0.775862,0.20,0.285714,0.00,0.0,married,rented,no,Technical_writer,Alappuzha,Kerala,0
3,0.344828,0.10,0.142857,0.50,1.0,single,rented,yes,Software_Developer,Bhubaneswar,Odisha,1
4,0.448276,0.55,0.214286,1.00,1.0,single,rented,no,Civil_servant,Tiruchirappalli[10],Tamil_Nadu,1

In [37]:
y = final_df['Risk_Flag']
X = final_df.drop('Risk_Flag', axis=1).values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Logistic regresion

In [42]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

ValueError: could not convert string to float: 'single'